import { Tile } from "@/types/tile";

export const MOCK_TILES: Tile[] = [
  {
    id: "1",
    title: "Azulejo Estrela",
    description: "Classic Portuguese star tile with deep cobalt blue hand-painting.",
    imageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800",
    category: "hand-painted",
    origin: "Portugal",
    tags: ["blue", "classic", "star"],
    featured: true,
    material: "Glazed ceramic",
    dimensions: "15×15 cm",
  },
  {
    id: "2",
    title: "Marrakech Grid",
    description: "Geometric encaustic tile inspired by Moroccan riads.",
    imageUrl: "https://images.unsplash.com/photo-1615529328331-f8917597711f?w=800",
    category: "geometric",
    origin: "Morocco",
    tags: ["geometric", "earth", "pattern"],
    featured: true,
    material: "Encaustic cement",
    dimensions: "20×20 cm",
  },
  {
    id: "3",
    title: "Rose Garden",
    description: "Delicate floral relief tile with Victorian-era charm.",
    imageUrl: "https://images.unsplash.com/photo-1578301978693-85fa9c0320b9?w=800",
    category: "floral",
    origin: "England",
    tags: ["floral", "relief", "pastel"],
    material: "Porcelain",
    dimensions: "10×10 cm",
  },
  {
    id: "4",
    title: "Terra Umbra",
    description: "Raw terracotta hex tile with natural earthy variation.",
    imageUrl: "https://images.unsplash.com/photo-1516455590571-18256e5bb9ff?w=800",
    category: "terracotta",
    origin: "Italy",
    tags: ["earth", "hex", "natural"],
    material: "Terracotta",
    dimensions: "17×15 cm",
  },
  {
    id: "5",
    title: "Byzantine Mosaic",
    description: "Intricate mosaic fragment reminiscent of Byzantine church interiors.",
    imageUrl: "https://images.unsplash.com/photo-1549887534-1541e9326688?w=800",
    category: "mosaic",
    origin: "Turkey",
    tags: ["mosaic", "gold", "intricate"],
    featured: true,
    material: "Glass & stone tesserae",
    dimensions: "30×30 cm",
  },
  {
    id: "6",
    title: "Cement Lace",
    description: "Modern interpretation of traditional lace motifs in cement.",
    imageUrl: "https://images.unsplash.com/photo-1540574163026-643ea20ade25?w=800",
    category: "encaustic",
    origin: "France",
    tags: ["lace", "white", "modern"],
    material: "Encaustic cement",
    dimensions: "20×20 cm",
  },
];
